// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../http/Http.res.mjs";
import * as Token from "../../shared/auth/Token.res.mjs";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as AdminConstants from "./AdminConstants.res.mjs";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

let optsNone = {};

function obj(xs) {
  let d = {};
  xs.forEach(param => {
    d[param[0]] = param[1];
  });
  return d;
}

function authOpts() {
  let t = Token.getToken();
  if (t !== undefined) {
    return obj([[
        "authToken",
        t
      ]]);
  } else {
    return optsNone;
  }
}

function dObj(j) {
  let o = Stdlib_JSON.Decode.object(j);
  if (o !== undefined) {
    return o;
  } else {
    return Stdlib_JsError.throwWithMessage("bad json");
  }
}

function dStr(o, k) {
  let v = Belt_Option.flatMap(o[k], Stdlib_JSON.Decode.string);
  if (v !== undefined) {
    return v;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function dAny(o, k) {
  let v = o[k];
  if (v !== undefined) {
    return v;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function decodeTestItem(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    task_id: dStr(o, "task_id"),
    name: dStr(o, "name"),
    input_json: dAny(o, "input_json"),
    expected_json: dAny(o, "expected_json")
  };
}

function list(taskId) {
  return Http.getJson(AdminConstants.base + "/tasks/" + taskId + "/tests", authOpts()).then(j => {
    let xs = Stdlib_JSON.Decode.array(j);
    if (xs !== undefined) {
      return Promise.resolve(xs.map(decodeTestItem));
    } else {
      return Stdlib_JsError.throwWithMessage("bad json");
    }
  });
}

function add(taskId, tests) {
  let body = tests.map(t => obj([
    [
      "name",
      t.name
    ],
    [
      "input_json",
      t.input_json
    ],
    [
      "expected_json",
      t.expected_json
    ],
    [
      "order_index",
      t.order_index
    ]
  ]));
  return Http.postJson(AdminConstants.base + "/tasks/" + taskId + "/tests", body, authOpts()).then(param => Promise.resolve(true));
}

function deleteOne(testId) {
  return Http.deleteJson(AdminConstants.base + "/task-tests/" + testId, authOpts()).then(param => Promise.resolve(true));
}

export {
  optsNone,
  obj,
  authOpts,
  dObj,
  dStr,
  dAny,
  decodeTestItem,
  list,
  add,
  deleteOne,
}
/* Http Not a pure module */
