// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../http/Http.res.mjs";
import * as Token from "../../shared/auth/Token.res.mjs";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as AdminConstants from "./AdminConstants.res.mjs";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

let optsNone = {};

function obj(xs) {
  let d = {};
  xs.forEach(param => {
    d[param[0]] = param[1];
  });
  return d;
}

function authOpts() {
  let t = Token.getToken();
  if (t !== undefined) {
    return obj([[
        "authToken",
        t
      ]]);
  } else {
    return optsNone;
  }
}

function dObj(j) {
  let o = Stdlib_JSON.Decode.object(j);
  if (o !== undefined) {
    return o;
  } else {
    return Stdlib_JsError.throwWithMessage("bad json");
  }
}

function dArr(j) {
  let xs = Stdlib_JSON.Decode.array(j);
  if (xs !== undefined) {
    return xs;
  } else {
    return Stdlib_JsError.throwWithMessage("bad json");
  }
}

function dStr(o, k) {
  let v = Belt_Option.flatMap(o[k], Stdlib_JSON.Decode.string);
  if (v !== undefined) {
    return v;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function dInt(o, k) {
  let v = o[k];
  if (v === undefined) {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
  let match = Stdlib_JSON.Decode.float(v);
  let match$1 = Stdlib_JSON.Decode.string(v);
  if (match !== undefined) {
    return match | 0;
  }
  if (match$1 === undefined) {
    return Stdlib_JsError.throwWithMessage("bad int " + k);
  }
  let i = Stdlib_Int.fromString(match$1, undefined);
  if (i !== undefined) {
    return i;
  } else {
    return Stdlib_JsError.throwWithMessage("bad int " + k);
  }
}

function dOptStr(o, k) {
  let v = o[k];
  if (v !== undefined) {
    return Stdlib_JSON.Decode.string(v);
  }
}

function decodeItem(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    title: dStr(o, "title"),
    subtitle: dStr(o, "subtitle"),
    created_at: dStr(o, "created_at"),
    archived_at: dOptStr(o, "archived_at")
  };
}

function decodePageTopic(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    title: dStr(o, "title"),
    subtitle: dStr(o, "subtitle"),
    archived_at: dOptStr(o, "archived_at")
  };
}

function decodeParagraph(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    sort_key: dInt(o, "sort_key"),
    body: dStr(o, "body"),
    code: dOptStr(o, "code")
  };
}

function decodePageTask(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    title: dStr(o, "title"),
    created_at: dStr(o, "created_at")
  };
}

function decodeTopicPageAdmin(j) {
  let o = dObj(j);
  let topic = decodePageTopic(Belt_Option.getExn(o["topic"]));
  let paragraphs = dArr(Belt_Option.getExn(o["paragraphs"])).map(decodeParagraph);
  let tasks = dArr(Belt_Option.getExn(o["tasks"])).map(decodePageTask);
  return {
    topic: topic,
    paragraphs: paragraphs,
    tasks: tasks
  };
}

function listAdmin() {
  return Http.getJson(AdminConstants.base + "/topics", authOpts()).then(j => Promise.resolve(dArr(j).map(decodeItem)));
}

function pageAdmin(id) {
  return Http.getJson(AdminConstants.base + "/topics/" + id + "/page", authOpts()).then(j => Promise.resolve(decodeTopicPageAdmin(j)));
}

function create(dto) {
  let body = obj([
    [
      "title",
      dto.title
    ],
    [
      "subtitle",
      dto.subtitle
    ]
  ]);
  return Http.postJson(AdminConstants.base + "/topics", body, authOpts()).then(j => {
    let o = dObj(j);
    return Promise.resolve({
      id: dStr(o, "id")
    });
  });
}

function archive(id) {
  return Http.putJson(AdminConstants.base + "/topics/" + id + "/archive", obj([]), authOpts()).then(param => Promise.resolve(true));
}

function unarchive(id) {
  return Http.putJson(AdminConstants.base + "/topics/" + id + "/unarchive", obj([]), authOpts()).then(param => Promise.resolve(true));
}

function addParagraphs(id, items) {
  let body = items.map(p => {
    let s = p.code;
    return obj([
      [
        "sort_key",
        p.sort_key
      ],
      [
        "body",
        p.body
      ],
      [
        "code",
        s !== undefined ? s : null
      ]
    ]);
  });
  return Http.postJson(AdminConstants.base + "/topics/" + id + "/paragraphs", body, authOpts()).then(param => Promise.resolve(true));
}

function deleteParagraph(id) {
  return Http.deleteJson(AdminConstants.base + "/topic-paragraphs/" + id, authOpts()).then(param => Promise.resolve(true));
}

export {
  optsNone,
  obj,
  authOpts,
  dObj,
  dArr,
  dStr,
  dInt,
  dOptStr,
  decodeItem,
  decodePageTopic,
  decodeParagraph,
  decodePageTask,
  decodeTopicPageAdmin,
  listAdmin,
  pageAdmin,
  create,
  archive,
  unarchive,
  addParagraphs,
  deleteParagraph,
}
/* Http Not a pure module */
