// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../http/Http.res.mjs";
import * as Token from "../../shared/auth/Token.res.mjs";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as AdminConstants from "./AdminConstants.res.mjs";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

let optsNone = {};

function obj(xs) {
  let d = {};
  xs.forEach(param => {
    d[param[0]] = param[1];
  });
  return d;
}

function authOpts() {
  let t = Token.getToken();
  if (t !== undefined) {
    return obj([[
        "authToken",
        t
      ]]);
  } else {
    return optsNone;
  }
}

function dObj(j) {
  let o = Stdlib_JSON.Decode.object(j);
  if (o !== undefined) {
    return o;
  } else {
    return Stdlib_JsError.throwWithMessage("bad json");
  }
}

function dArr(j) {
  let xs = Stdlib_JSON.Decode.array(j);
  if (xs !== undefined) {
    return xs;
  } else {
    return Stdlib_JsError.throwWithMessage("bad json");
  }
}

function dStr(o, k) {
  let v = Belt_Option.flatMap(o[k], Stdlib_JSON.Decode.string);
  if (v !== undefined) {
    return v;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function dOptStr(o, k) {
  let v = o[k];
  if (v !== undefined) {
    return Stdlib_JSON.Decode.string(v);
  }
}

function decodeTask(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    topic_id: dStr(o, "topic_id"),
    title: dStr(o, "title"),
    statement: dStr(o, "statement"),
    starter_code: dStr(o, "starter_code"),
    runner: dStr(o, "runner"),
    runner_body: dStr(o, "runner_body"),
    created_at: dStr(o, "created_at"),
    archived_at: dOptStr(o, "archived_at")
  };
}

function decodeCreate(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id")
  };
}

function list() {
  return Http.getJson(AdminConstants.base + "/tasks", authOpts()).then(j => Promise.resolve(dArr(j).map(decodeTask)));
}

function getOne(id) {
  return Http.getJson(AdminConstants.base + "/tasks/" + id, authOpts()).then(j => Promise.resolve(decodeTask(j)));
}

function create(dto) {
  let d = {};
  d["topic_id"] = dto.topic_id;
  d["title"] = dto.title;
  d["statement"] = dto.statement;
  d["starter_code"] = dto.starter_code;
  let r = dto.runner;
  if (r !== undefined) {
    d["runner"] = r;
  }
  let rb = dto.runner_body;
  if (rb !== undefined) {
    d["runner_body"] = rb;
  }
  return Http.postJson(AdminConstants.base + "/tasks", d, authOpts()).then(j => Promise.resolve(decodeCreate(j)));
}

function archive(id) {
  return Http.putJson(AdminConstants.base + "/tasks/" + id + "/archive", obj([]), authOpts()).then(param => Promise.resolve(true));
}

function unarchive(id) {
  return Http.putJson(AdminConstants.base + "/tasks/" + id + "/unarchive", obj([]), authOpts()).then(param => Promise.resolve(true));
}

export {
  optsNone,
  obj,
  authOpts,
  dObj,
  dArr,
  dStr,
  dOptStr,
  decodeTask,
  decodeCreate,
  list,
  getOne,
  create,
  archive,
  unarchive,
}
/* Http Not a pure module */
