// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JwtJs from "./jwt.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function getRole(prim) {
  return Primitive_option.fromNullable(JwtJs.getRole());
}

function isAdmin(prim) {
  return JwtJs.isAdmin();
}

export {
  getRole,
  isAdmin,
}
/* ./jwt.js Not a pure module */
