// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TokenJs from "./token.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function getToken(prim) {
  return Primitive_option.fromNullable(TokenJs.getToken());
}

function setToken(prim) {
  TokenJs.setToken(prim);
}

function clearToken(prim) {
  TokenJs.clearToken();
}

export {
  getToken,
  setToken,
  clearToken,
}
/* ./token.js Not a pure module */
