// Generated by ReScript, PLEASE EDIT WITH CARE


function toString(t) {
  if (t === "White") {
    return "white";
  } else {
    return "black";
  }
}

function fromString(s) {
  if (s === "black") {
    return "Black";
  } else {
    return "White";
  }
}

export {
  toString,
  fromString,
}
/* No side effect */
