// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HttpJs from "./http.js";

function getJson(prim0, prim1) {
  return HttpJs.getJson(prim0, prim1);
}

function postJson(prim0, prim1, prim2) {
  return HttpJs.postJson(prim0, prim1, prim2);
}

function putJson(prim0, prim1, prim2) {
  return HttpJs.putJson(prim0, prim1, prim2);
}

function patchJson(prim0, prim1, prim2) {
  return HttpJs.patchJson(prim0, prim1, prim2);
}

function deleteJson(prim0, prim1) {
  return HttpJs.deleteJson(prim0, prim1);
}

export {
  getJson,
  postJson,
  putJson,
  patchJson,
  deleteJson,
}
/* ./http.js Not a pure module */
