// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../http/Http.res.mjs";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as AuthConstants from "./AuthConstants.res.mjs";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

let emptyObj = {};

let d = {};

d["skipAuth"] = true;

function decodeObj(j) {
  let o = Stdlib_JSON.Decode.object(j);
  if (o !== undefined) {
    return o;
  } else {
    return Stdlib_JsError.throwWithMessage("bad json");
  }
}

function getString(o, k) {
  let s = Belt_Option.flatMap(o[k], Stdlib_JSON.Decode.string);
  if (s !== undefined) {
    return s;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function getInt(o, k) {
  let n = Belt_Option.flatMap(o[k], Stdlib_JSON.Decode.float);
  if (n !== undefined) {
    return n | 0;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function decodeAuthResponse(j) {
  let o = decodeObj(j);
  return {
    token: getString(o, "token")
  };
}

function decodeMe(j) {
  let o = decodeObj(j);
  return {
    id: getString(o, "id"),
    role: getString(o, "role"),
    email: getString(o, "email"),
    nickname: getString(o, "nickname"),
    rating: getInt(o, "rating")
  };
}

function login(dto) {
  let d$1 = {};
  d$1["email"] = dto.email;
  d$1["password"] = dto.password;
  return Http.postJson(AuthConstants.authApiBase + "/login", d$1, d).then(j => Promise.resolve(decodeAuthResponse(j)));
}

function register(dto) {
  let d$1 = {};
  d$1["email"] = dto.email;
  d$1["password"] = dto.password;
  d$1["nickname"] = dto.nickname;
  return Http.postJson(AuthConstants.authApiBase + "/register", d$1, d).then(j => Promise.resolve(decodeAuthResponse(j)));
}

function me(token) {
  let d = {};
  d["authToken"] = token;
  return Http.getJson(AuthConstants.authApiBase + "/me", d).then(j => Promise.resolve(decodeMe(j)));
}

let optsNone = emptyObj;

let optsSkipAuth = d;

export {
  emptyObj,
  optsNone,
  optsSkipAuth,
  decodeObj,
  getString,
  getInt,
  decodeAuthResponse,
  decodeMe,
  login,
  register,
  me,
}
/*  Not a pure module */
