// Generated by ReScript, PLEASE EDIT WITH CARE


let apiUrl = (process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080");

let authApiBase = apiUrl + "/auth";

export {
  apiUrl,
  authApiBase,
}
/* apiUrl Not a pure module */
