// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../http/Http.res.mjs";
import * as Token from "../../shared/auth/Token.res.mjs";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

let optsNone = {};

function obj(xs) {
  let d = {};
  xs.forEach(param => {
    d[param[0]] = param[1];
  });
  return d;
}

function authOpts() {
  let t = Token.getToken();
  if (t !== undefined) {
    return obj([[
        "authToken",
        t
      ]]);
  } else {
    return optsNone;
  }
}

function dObj(j) {
  let o = Stdlib_JSON.Decode.object(j);
  if (o !== undefined) {
    return o;
  } else {
    return Stdlib_JsError.throwWithMessage("bad json");
  }
}

function dArr(j) {
  let xs = Stdlib_JSON.Decode.array(j);
  if (xs !== undefined) {
    return xs;
  } else {
    return Stdlib_JsError.throwWithMessage("bad json");
  }
}

function dStr(o, k) {
  let v = Belt_Option.flatMap(o[k], Stdlib_JSON.Decode.string);
  if (v !== undefined) {
    return v;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function dInt(o, k) {
  let v = o[k];
  if (v === undefined) {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
  let match = Stdlib_JSON.Decode.float(v);
  let match$1 = Stdlib_JSON.Decode.string(v);
  if (match !== undefined) {
    return match | 0;
  }
  if (match$1 === undefined) {
    return Stdlib_JsError.throwWithMessage("bad int " + k);
  }
  let i = Stdlib_Int.fromString(match$1, undefined);
  if (i !== undefined) {
    return i;
  } else {
    return Stdlib_JsError.throwWithMessage("bad int " + k);
  }
}

function dOptStr(o, k) {
  let v = o[k];
  if (v !== undefined) {
    return Stdlib_JSON.Decode.string(v);
  }
}

function decodeTopic(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    title: dStr(o, "title"),
    subtitle: dStr(o, "subtitle"),
    created_at: dStr(o, "created_at")
  };
}

function decodePageTopic(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    title: dStr(o, "title"),
    subtitle: dStr(o, "subtitle")
  };
}

function decodeParagraph(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    sort_key: dInt(o, "sort_key"),
    body: dStr(o, "body"),
    code: dOptStr(o, "code")
  };
}

function decodePageTask(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    title: dStr(o, "title"),
    created_at: dStr(o, "created_at")
  };
}

function decodeTopicPage(j) {
  let o = dObj(j);
  let topic = decodePageTopic(Belt_Option.getExn(o["topic"]));
  let paragraphs = dArr(Belt_Option.getExn(o["paragraphs"])).map(decodeParagraph);
  let tasks = dArr(Belt_Option.getExn(o["tasks"])).map(decodePageTask);
  return {
    topic: topic,
    paragraphs: paragraphs,
    tasks: tasks
  };
}

function list() {
  return Http.getJson("/topics", optsNone).then(j => Promise.resolve(dArr(j).map(decodeTopic)));
}

function page(id) {
  return Http.getJson("/topics/" + id + "/page", optsNone).then(j => Promise.resolve(decodeTopicPage(j)));
}

function paragraphs(id) {
  return Http.getJson("/topics/" + id + "/paragraphs", optsNone).then(j => Promise.resolve(dArr(j).map(decodeParagraph)));
}

export {
  optsNone,
  obj,
  authOpts,
  dObj,
  dArr,
  dStr,
  dInt,
  dOptStr,
  decodeTopic,
  decodePageTopic,
  decodeParagraph,
  decodePageTask,
  decodeTopicPage,
  list,
  page,
  paragraphs,
}
/* Http Not a pure module */
