// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ThemeProvider from "./shared/theme/ThemeProvider.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
    children: [
      JsxRuntime.jsx(ThemeProvider.make, {}),
      props.children
    ]
  });
}

let make = App;

export {
  make,
}
/* ThemeProvider Not a pure module */
