// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ThemeStore from "./ThemeStore.res.mjs";

function ThemeProvider(props) {
  let themeStr = ThemeStore.useThemeStore(s => s.theme);
  React.useEffect(() => {
    let el = document.documentElement;
    el.setAttribute("data-theme", themeStr);
  }, [themeStr]);
  return null;
}

let make = ThemeProvider;

export {
  make,
}
/* react Not a pure module */
