// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ThemeStoreJs from "./themeStore.js";

function useThemeStore(prim) {
  return ThemeStoreJs.useThemeStore(prim);
}

export {
  useThemeStore,
}
/* ./themeStore.js Not a pure module */
