// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NextImage from "../../bindings/NextImage.res.mjs";
import * as ThemeStore from "./ThemeStore.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function ThemedIcon(props) {
  let height = props.height;
  let width = props.width;
  let themeStr = ThemeStore.useThemeStore(s => s.theme);
  let color = themeStr === "black" ? "white" : "black";
  let w = width !== undefined ? width : 15;
  let h = height !== undefined ? height : 15;
  return JsxRuntime.jsx(NextImage.make, {
    src: props.path + "_" + color + ".svg",
    width: w,
    height: h,
    alt: "",
    className: props.className,
    priority: true
  });
}

let make = ThemedIcon;

export {
  make,
}
/* NextImage Not a pure module */
