// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NextImage from "../../bindings/NextImage.res.mjs";
import * as ThemeStore from "./ThemeStore.res.mjs";
import * as ThemedIcon from "./ThemedIcon.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import ThemeSwitcherModuleScss from "./ThemeSwitcher.module.scss";

let styles = ThemeSwitcherModuleScss;

function cx(a, b) {
  return a + " " + b;
}

function ThemeSwitcher(props) {
  let themeStr = ThemeStore.useThemeStore(s => s.theme);
  let setTheme = ThemeStore.useThemeStore(s => s.setTheme);
  let moonClass = themeStr === "black" ? cx(cx(styles.theme__button, styles.moon), styles.current) : cx(styles.theme__button, styles.moon);
  let sunClass = themeStr === "white" ? cx(cx(styles.theme__button, styles.sun), styles.current) : cx(styles.theme__button, styles.sun);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("button", {
        children: JsxRuntime.jsx(NextImage.make, {
          src: "/themed_icons/moon.svg",
          width: 15,
          height: 15,
          alt: "moon",
          className: styles.moonIcon,
          priority: true
        }),
        className: moonClass,
        type: "button",
        onClick: param => setTheme("black")
      }),
      JsxRuntime.jsx("button", {
        children: JsxRuntime.jsx(ThemedIcon.make, {
          path: "/themed_icons/sun"
        }),
        className: sunClass,
        type: "button",
        onClick: param => setTheme("white")
      })
    ],
    className: styles.theme
  });
}

let make = ThemeSwitcher;

export {
  styles,
  cx,
  make,
}
/* styles Not a pure module */
