// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../http/Http.res.mjs";
import * as Token from "../../shared/auth/Token.res.mjs";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as UsersConstants from "./UsersConstants.res.mjs";

let optsNone = {};

function obj(xs) {
  let d = {};
  xs.forEach(param => {
    d[param[0]] = param[1];
  });
  return d;
}

function authOpts() {
  let t = Token.getToken();
  if (t !== undefined) {
    return obj([[
        "authToken",
        t
      ]]);
  } else {
    return optsNone;
  }
}

function dObj(j) {
  let o = Stdlib_JSON.Decode.object(j);
  if (o !== undefined) {
    return o;
  } else {
    return Stdlib_JsError.throwWithMessage("bad json");
  }
}

function dStr(o, k) {
  let v = Belt_Option.flatMap(o[k], Stdlib_JSON.Decode.string);
  if (v !== undefined) {
    return v;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function dInt(o, k) {
  let v = Belt_Option.flatMap(o[k], Stdlib_JSON.Decode.float);
  if (v !== undefined) {
    return v | 0;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function dArr(o, k) {
  let v = Belt_Option.flatMap(o[k], Stdlib_JSON.Decode.array);
  if (v !== undefined) {
    return v;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function decodeMe(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    email: dStr(o, "email"),
    nickname: dStr(o, "nickname"),
    role: dStr(o, "role"),
    rating: dInt(o, "rating")
  };
}

function decodeLeaderboardItem(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    email: dStr(o, "email"),
    nickname: dStr(o, "nickname"),
    rating: dInt(o, "rating")
  };
}

function decodeLeaderboard(j) {
  let o = dObj(j);
  let items = dArr(o, "items").map(decodeLeaderboardItem);
  return {
    limit: dInt(o, "limit"),
    offset: dInt(o, "offset"),
    items: items
  };
}

function me() {
  return Http.getJson(UsersConstants.base + "/me", authOpts()).then(j => Promise.resolve(decodeMe(j)));
}

function leaderboard(limit, offset) {
  let q;
  let exit = 0;
  if (limit !== undefined || offset !== undefined) {
    exit = 1;
  } else {
    q = "";
  }
  if (exit === 1) {
    let l = limit !== undefined ? "limit=" + limit.toString() : "";
    let o = offset !== undefined ? "offset=" + offset.toString() : "";
    let sep = l !== "" && o !== "" ? "&" : "";
    q = "?" + l + sep + o;
  }
  return Http.getJson(UsersConstants.base + "/leaderboard" + q, optsNone).then(j => Promise.resolve(decodeLeaderboard(j)));
}

export {
  optsNone,
  obj,
  authOpts,
  dObj,
  dStr,
  dInt,
  dArr,
  decodeMe,
  decodeLeaderboardItem,
  decodeLeaderboard,
  me,
  leaderboard,
}
/* Http Not a pure module */
