// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../http/Http.res.mjs";
import * as Token from "../../shared/auth/Token.res.mjs";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

let optsNone = {};

function obj(xs) {
  let d = {};
  xs.forEach(param => {
    d[param[0]] = param[1];
  });
  return d;
}

function dObj(j) {
  let o = Stdlib_JSON.Decode.object(j);
  if (o !== undefined) {
    return o;
  } else {
    return Stdlib_JsError.throwWithMessage("bad json");
  }
}

function dArr(j) {
  let xs = Stdlib_JSON.Decode.array(j);
  if (xs !== undefined) {
    return xs;
  } else {
    return Stdlib_JsError.throwWithMessage("bad json");
  }
}

function dStr(o, k) {
  let v = Belt_Option.flatMap(o[k], Stdlib_JSON.Decode.string);
  if (v !== undefined) {
    return v;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function dInt(o, k) {
  let v = Belt_Option.flatMap(o[k], Stdlib_JSON.Decode.float);
  if (v !== undefined) {
    return v | 0;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function dArrField(o, k) {
  let v = Belt_Option.flatMap(o[k], Stdlib_JSON.Decode.array);
  if (v !== undefined) {
    return v;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function authOpts() {
  let t = Token.getToken();
  if (t !== undefined) {
    return obj([[
        "authToken",
        t
      ]]);
  } else {
    return optsNone;
  }
}

function decodeTaskListItem(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    topic_id: dStr(o, "topic_id"),
    title: dStr(o, "title"),
    created_at: dStr(o, "created_at")
  };
}

function decodeTask(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    topic_id: dStr(o, "topic_id"),
    title: dStr(o, "title"),
    statement: dStr(o, "statement"),
    starter_code: dStr(o, "starter_code"),
    runner: dStr(o, "runner"),
    runner_body: dStr(o, "runner_body")
  };
}

function decodeSubmit(j) {
  let o = dObj(j);
  return {
    submission_id: dStr(o, "submission_id"),
    status: dStr(o, "status"),
    score: dInt(o, "score"),
    delta: dInt(o, "delta"),
    rating: dInt(o, "rating")
  };
}

function decodeMySubmissionItem(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    status: dStr(o, "status"),
    score: dInt(o, "score"),
    passed_tests: dInt(o, "passed_tests"),
    total_tests: dInt(o, "total_tests"),
    created_at: dStr(o, "created_at")
  };
}

function decodeMySubmissions(j) {
  let o = dObj(j);
  let items = dArrField(o, "items").map(decodeMySubmissionItem);
  return {
    limit: dInt(o, "limit"),
    offset: dInt(o, "offset"),
    items: items
  };
}

function decodeMyTaskItem(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    topic_id: dStr(o, "topic_id"),
    title: dStr(o, "title"),
    created_at: dStr(o, "created_at"),
    best_score: dInt(o, "best_score")
  };
}

function decodeMyBest(j) {
  let o = dObj(j);
  return {
    best_score: dInt(o, "best_score")
  };
}

function listAll() {
  return Http.getJson("/tasks", optsNone).then(j => Promise.resolve(dArr(j).map(decodeTaskListItem)));
}

function listByTopic(topicId) {
  return Http.getJson("/topics/" + topicId + "/tasks", optsNone).then(j => Promise.resolve(dArr(j).map(decodeTaskListItem)));
}

function getOne(id) {
  return Http.getJson("/tasks/" + id, optsNone).then(j => Promise.resolve(decodeTask(j)));
}

function submit(id, code) {
  let body = obj([[
      "code",
      code
    ]]);
  return Http.postJson("/tasks/" + id + "/submit", body, authOpts()).then(j => Promise.resolve(decodeSubmit(j)));
}

function mySubmissions(id, limit, offset) {
  let q;
  let exit = 0;
  if (limit !== undefined || offset !== undefined) {
    exit = 1;
  } else {
    q = "";
  }
  if (exit === 1) {
    let l = limit !== undefined ? "limit=" + limit.toString() : "";
    let o = offset !== undefined ? "offset=" + offset.toString() : "";
    let sep = l !== "" && o !== "" ? "&" : "";
    q = "?" + l + sep + o;
  }
  return Http.getJson("/tasks/" + id + "/submissions" + q, authOpts()).then(j => Promise.resolve(decodeMySubmissions(j)));
}

function myTasks() {
  return Http.getJson("/tasks/my", authOpts()).then(j => {
    let xs = Stdlib_JSON.Decode.array(j);
    if (xs !== undefined) {
      return Promise.resolve(xs.map(decodeMyTaskItem));
    } else {
      return Stdlib_JsError.throwWithMessage("bad json");
    }
  });
}

function myBest(id) {
  return Http.getJson("/tasks/" + id + "/my-best", authOpts()).then(j => Promise.resolve(decodeMyBest(j)));
}

export {
  optsNone,
  obj,
  dObj,
  dArr,
  dStr,
  dInt,
  dArrField,
  authOpts,
  decodeTaskListItem,
  decodeTask,
  decodeSubmit,
  decodeMySubmissionItem,
  decodeMySubmissions,
  decodeMyTaskItem,
  decodeMyBest,
  listAll,
  listByTopic,
  getOne,
  submit,
  mySubmissions,
  myTasks,
  myBest,
}
/* Http Not a pure module */
