// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Token from "../../shared/auth/Token.res.mjs";
import * as React from "react";
import * as UsersApi from "../../api/users/UsersApi.res.mjs";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as ProfileModuleScss from "./Profile.module.scss";

let page = ProfileModuleScss.page;

let top = ProfileModuleScss.top;

let h1 = ProfileModuleScss.h1;

let sub = ProfileModuleScss.sub;

let card = ProfileModuleScss.card;

let row = ProfileModuleScss.row;

let label = ProfileModuleScss.label;

let value = ProfileModuleScss.value;

let actions = ProfileModuleScss.actions;

let btn = ProfileModuleScss.btn;

let danger = ProfileModuleScss.danger;

let S = {
  page: page,
  top: top,
  h1: h1,
  sub: sub,
  card: card,
  row: row,
  label: label,
  value: value,
  actions: actions,
  btn: btn,
  danger: danger
};

function errMsg(e) {
  let m = Stdlib_JsExn.message(e);
  if (m !== undefined) {
    return m;
  } else {
    return "error";
  }
}

function logout() {
  Token.clearToken();
  window.location.reload();
}

function Profile(props) {
  let match = React.useState(() => {});
  let setMe = match[1];
  let me = match[0];
  let match$1 = React.useState(() => "");
  let setErr = match$1[1];
  let err = match$1[0];
  let match$2 = React.useState(() => true);
  let setLoading = match$2[1];
  React.useEffect(() => {
    setLoading(param => true);
    Stdlib_Promise.$$catch(UsersApi.me().then(m => {
      setMe(param => m);
      setErr(param => "");
      setLoading(param => false);
      return Promise.resolve();
    }), e => {
      setErr(param => errMsg(e));
      setLoading(param => false);
      return Promise.resolve();
    });
  }, []);
  let tmp = err === "" ? null : JsxRuntime.jsx("div", {
      children: "Error: " + err,
      className: sub
    });
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: "Profile",
                className: h1
              }),
              JsxRuntime.jsx("div", {
                children: match$2[0] ? "Loading..." : (
                    me !== undefined ? "Signed in as " + me.nickname : "Not loaded"
                  ),
                className: sub
              })
            ]
          }),
          JsxRuntime.jsx("button", {
            children: "Logout",
            className: btn + " " + danger,
            onClick: param => logout()
          })
        ],
        className: top
      }),
      tmp,
      me !== undefined ? JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                  children: "Nickname",
                  className: label
                }),
                JsxRuntime.jsx("div", {
                  children: me.nickname,
                  className: value
                })
              ],
              className: row
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                  children: "Email",
                  className: label
                }),
                JsxRuntime.jsx("div", {
                  children: me.email,
                  className: value
                })
              ],
              className: row
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                  children: "Role",
                  className: label
                }),
                JsxRuntime.jsx("div", {
                  children: me.role,
                  className: value
                })
              ],
              className: row
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                  children: "Rating",
                  className: label
                }),
                JsxRuntime.jsx("div", {
                  children: me.rating.toString(),
                  className: value
                })
              ],
              className: row
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                  children: "ID",
                  className: label
                }),
                JsxRuntime.jsx("div", {
                  children: me.id,
                  className: value
                })
              ],
              className: row
            })
          ],
          className: card
        }) : null
    ],
    className: page
  });
}

let make = Profile;

export {
  S,
  errMsg,
  logout,
  make,
}
/* page Not a pure module */
