// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jwt from "../auth/Jwt.res.mjs";
import * as React from "react";
import * as NextLink from "../../bindings/NextLink.res.mjs";
import * as ThemedIcon from "../theme/ThemedIcon.res.mjs";
import * as ThemeSwitcher from "../theme/ThemeSwitcher.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as HeaderModuleScss from "./Header.module.scss";

let header = HeaderModuleScss.header;

let brand = HeaderModuleScss.brand;

let center = HeaderModuleScss.center;

let nav = HeaderModuleScss.nav;

let navBtn = HeaderModuleScss.navBtn;

let right = HeaderModuleScss.right;

let iconBtn = HeaderModuleScss.iconBtn;

let adminBtn = HeaderModuleScss.adminBtn;

let theme = HeaderModuleScss.theme;

let theme__button = HeaderModuleScss.theme__button;

let moon = HeaderModuleScss.moon;

let sun = HeaderModuleScss.sun;

let current = HeaderModuleScss.current;

let moonIcon = HeaderModuleScss.moonIcon;

let S = {
  header: header,
  brand: brand,
  center: center,
  nav: nav,
  navBtn: navBtn,
  right: right,
  iconBtn: iconBtn,
  adminBtn: adminBtn,
  theme: theme,
  theme__button: theme__button,
  moon: moon,
  sun: sun,
  current: current,
  moonIcon: moonIcon
};

let addListener = ((name, cb) => { if (typeof window === "undefined") return () => {}; window.addEventListener(name, cb); return () => window.removeEventListener(name, cb); });

function Header(props) {
  let match = React.useState(() => Jwt.isAdmin());
  let setIsAdmin = match[1];
  React.useEffect(() => {
    setIsAdmin(param => Jwt.isAdmin());
    let cb = param => setIsAdmin(param => Jwt.isAdmin());
    let off1 = addListener("auth-changed", cb);
    let off2 = addListener("storage", cb);
    let off3 = addListener("focus", cb);
    return () => {
      off1();
      off2();
      off3();
    };
  }, []);
  return JsxRuntime.jsxs("header", {
    children: [
      JsxRuntime.jsx(NextLink.make, {
        href: "/",
        className: brand,
        children: "PF"
      }),
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx(NextLink.make, {
              href: "/",
              className: navBtn,
              children: "Topics"
            }),
            JsxRuntime.jsx(NextLink.make, {
              href: "/leaderboard",
              className: navBtn,
              children: "Leaderboard"
            })
          ],
          className: nav
        }),
        className: center
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx(NextLink.make, {
            href: "/profile",
            className: iconBtn,
            children: JsxRuntime.jsx(ThemedIcon.make, {
              path: "/themed_icons/profile",
              width: 20,
              height: 20
            })
          }),
          match[0] ? JsxRuntime.jsx(NextLink.make, {
              href: "/admin",
              className: adminBtn,
              children: "Admin"
            }) : null,
          JsxRuntime.jsx(ThemeSwitcher.make, {})
        ],
        className: right
      })
    ],
    className: header
  });
}

let make = Header;

export {
  S,
  addListener,
  make,
}
/* header Not a pure module */
