// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../http/Http.res.mjs";
import * as Token from "../../shared/auth/Token.res.mjs";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

let optsNone = {};

function obj(xs) {
  let d = {};
  xs.forEach(param => {
    d[param[0]] = param[1];
  });
  return d;
}

function authOpts() {
  let t = Token.getToken();
  if (t !== undefined) {
    return obj([[
        "authToken",
        t
      ]]);
  } else {
    return optsNone;
  }
}

function dObj(j) {
  let o = Stdlib_JSON.Decode.object(j);
  if (o !== undefined) {
    return o;
  } else {
    return Stdlib_JsError.throwWithMessage("bad json");
  }
}

function dStr(o, k) {
  let v = Belt_Option.flatMap(o[k], Stdlib_JSON.Decode.string);
  if (v !== undefined) {
    return v;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function dInt(o, k) {
  let v = Belt_Option.flatMap(o[k], Stdlib_JSON.Decode.float);
  if (v !== undefined) {
    return v | 0;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function dAny(o, k) {
  let v = o[k];
  if (v !== undefined) {
    return v;
  } else {
    return Stdlib_JsError.throwWithMessage("missing " + k);
  }
}

function decodeSubmission(j) {
  let o = dObj(j);
  return {
    id: dStr(o, "id"),
    status: dStr(o, "status"),
    score: dInt(o, "score"),
    passed_tests: dInt(o, "passed_tests"),
    total_tests: dInt(o, "total_tests"),
    result: dAny(o, "result")
  };
}

function getOne(id) {
  return Http.getJson("/submissions/" + id, authOpts()).then(j => Promise.resolve(decodeSubmission(j)));
}

export {
  optsNone,
  obj,
  authOpts,
  dObj,
  dStr,
  dInt,
  dAny,
  decodeSubmission,
  getOne,
}
/* Http Not a pure module */
