// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NextLink from "../../bindings/NextLink.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as AdminTopicsApi from "../../api/admin/AdminTopicsApi.res.mjs";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as AdminTopicsModuleScss from "./AdminTopics.module.scss";

let page = AdminTopicsModuleScss.page;

let top = AdminTopicsModuleScss.top;

let h1 = AdminTopicsModuleScss.h1;

let sub = AdminTopicsModuleScss.sub;

let btn = AdminTopicsModuleScss.btn;

let card = AdminTopicsModuleScss.card;

let h2 = AdminTopicsModuleScss.h2;

let grid = AdminTopicsModuleScss.grid;

let field = AdminTopicsModuleScss.field;

let label = AdminTopicsModuleScss.label;

let input = AdminTopicsModuleScss.input;

let row = AdminTopicsModuleScss.row;

let smallBtn = AdminTopicsModuleScss.smallBtn;

let pill = AdminTopicsModuleScss.pill;

let error = AdminTopicsModuleScss.error;

let list = AdminTopicsModuleScss.list;

let item = AdminTopicsModuleScss.item;

let left = AdminTopicsModuleScss.left;

let title = AdminTopicsModuleScss.title;

let meta = AdminTopicsModuleScss.meta;

let actions = AdminTopicsModuleScss.actions;

let badge = AdminTopicsModuleScss.badge;

let S = {
  page: page,
  top: top,
  h1: h1,
  sub: sub,
  btn: btn,
  card: card,
  h2: h2,
  grid: grid,
  field: field,
  label: label,
  input: input,
  row: row,
  smallBtn: smallBtn,
  pill: pill,
  error: error,
  list: list,
  item: item,
  left: left,
  title: title,
  meta: meta,
  actions: actions,
  badge: badge
};

function errMsg(e) {
  let m = Stdlib_JsExn.message(e);
  if (m !== undefined) {
    return m;
  } else {
    return "error";
  }
}

let includesLower = ((s,q)=>String(s).toLowerCase().includes(String(q)));

function AdminTopics(props) {
  let match = React.useState(() => []);
  let setItems = match[1];
  let items = match[0];
  let match$1 = React.useState(() => true);
  let setLoading = match$1[1];
  let loading = match$1[0];
  let match$2 = React.useState(() => "");
  let setErr = match$2[1];
  let err = match$2[0];
  let match$3 = React.useState(() => "");
  let setTitle = match$3[1];
  let title$1 = match$3[0];
  let match$4 = React.useState(() => "");
  let setSubtitle = match$4[1];
  let subtitle = match$4[0];
  let match$5 = React.useState(() => false);
  let setCreating = match$5[1];
  let creating = match$5[0];
  let match$6 = React.useState(() => "");
  let setFilter = match$6[1];
  let filter = match$6[0];
  let match$7 = React.useState(() => false);
  let setShowArchived = match$7[1];
  let showArchived = match$7[0];
  let load = () => {
    setLoading(param => true);
    setErr(param => "");
    Stdlib_Promise.$$catch(AdminTopicsApi.listAdmin().then(xs => {
      setItems(param => xs);
      setLoading(param => false);
      return Promise.resolve();
    }), e => {
      setErr(param => errMsg(e));
      setLoading(param => false);
      return Promise.resolve();
    });
  };
  React.useEffect(() => {
    load();
  }, []);
  let onCreate = () => {
    if (title$1.trim() === "") {
      return setErr(param => "Title is required");
    } else {
      setCreating(param => true);
      setErr(param => "");
      Stdlib_Promise.$$catch(AdminTopicsApi.create({
        title: title$1,
        subtitle: subtitle
      }).then(param => {
        setTitle(param => "");
        setSubtitle(param => "");
        setCreating(param => false);
        load();
        return Promise.resolve();
      }), e => {
        setErr(param => errMsg(e));
        setCreating(param => false);
        return Promise.resolve();
      });
      return;
    }
  };
  let q = filter.trim().toLowerCase();
  let visible = Belt_Array.keep(items, it => {
    let match = it.archived_at;
    let okArchived = showArchived ? true : match === undefined;
    let okFilter = q === "" ? true : includesLower(it.title, q) || includesLower(it.subtitle, q) || includesLower(it.id, q);
    if (okArchived) {
      return okFilter;
    } else {
      return false;
    }
  });
  let tmp = err === "" ? null : JsxRuntime.jsx("div", {
      children: "Error: " + err,
      className: error
    });
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: "Topics (admin)",
                className: h1
              }),
              JsxRuntime.jsx("div", {
                children: loading ? "Loading..." : visible.length.toString() + " topics",
                className: sub
              }),
              tmp
            ]
          }),
          JsxRuntime.jsx(NextLink.make, {
            href: "/admin",
            className: btn,
            children: "Back"
          })
        ],
        className: top
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Create topic",
            className: h2
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: "Title",
                    className: label
                  }),
                  JsxRuntime.jsx("input", {
                    className: input,
                    value: title$1,
                    onChange: e => setTitle(param => e.target.value)
                  })
                ],
                className: field
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: "Subtitle",
                    className: label
                  }),
                  JsxRuntime.jsx("input", {
                    className: input,
                    value: subtitle,
                    onChange: e => setSubtitle(param => e.target.value)
                  })
                ],
                className: field
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("button", {
                    children: creating ? "Creating..." : "Create",
                    className: smallBtn,
                    disabled: creating,
                    onClick: param => onCreate()
                  }),
                  JsxRuntime.jsx("button", {
                    children: loading ? "Reloading..." : "Reload",
                    className: smallBtn,
                    disabled: loading,
                    onClick: param => load()
                  })
                ],
                className: row
              })
            ],
            className: grid
          })
        ],
        className: card
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Topics",
            className: h2
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: "Filter",
                    className: label
                  }),
                  JsxRuntime.jsx("input", {
                    className: input,
                    value: filter,
                    onChange: e => setFilter(param => e.target.value)
                  })
                ],
                className: field
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("button", {
                    children: showArchived ? "Showing archived" : "Hide archived",
                    className: smallBtn,
                    onClick: param => setShowArchived(v => !v)
                  }),
                  JsxRuntime.jsx("div", {
                    children: "Total: " + items.length.toString(),
                    className: pill
                  })
                ],
                className: row
              })
            ],
            className: grid
          }),
          JsxRuntime.jsx("div", {
            children: Belt_Array.map(visible, it => {
              let match = it.archived_at;
              let archived = match !== undefined;
              let s = it.archived_at;
              return JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                        children: it.title + (
                          archived ? " (archived)" : ""
                        ),
                        className: title
                      }),
                      JsxRuntime.jsx("div", {
                        children: it.subtitle === "" ? "—" : it.subtitle,
                        className: meta
                      }),
                      JsxRuntime.jsx("div", {
                        children: "id " + it.id + " • " + it.created_at,
                        className: meta
                      }),
                      s !== undefined ? JsxRuntime.jsx("div", {
                          children: "archived_at " + s,
                          className: badge
                        }) : null
                    ],
                    className: left
                  }),
                  JsxRuntime.jsx("div", {
                    children: archived ? JsxRuntime.jsx("button", {
                        children: "Unarchive",
                        className: smallBtn,
                        onClick: param => {
                          let id = it.id;
                          AdminTopicsApi.unarchive(id).then(param => {
                            load();
                            return Promise.resolve();
                          });
                        }
                      }) : JsxRuntime.jsx("button", {
                        children: "Archive",
                        className: smallBtn,
                        onClick: param => {
                          let id = it.id;
                          AdminTopicsApi.archive(id).then(param => {
                            load();
                            return Promise.resolve();
                          });
                        }
                      }),
                    className: actions
                  })
                ],
                className: item
              }, it.id);
            }),
            className: list
          })
        ],
        className: card
      })
    ],
    className: page
  });
}

let make = AdminTopics;

export {
  S,
  errMsg,
  includesLower,
  make,
}
/* page Not a pure module */
