// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NextLink from "../../bindings/NextLink.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as AdminTasksApi from "../../api/admin/AdminTasksApi.res.mjs";
import * as AdminTestsApi from "../../api/admin/AdminTestsApi.res.mjs";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as AdminTasksModuleScss from "./AdminTasks.module.scss";

let page = AdminTasksModuleScss.page;

let top = AdminTasksModuleScss.top;

let h1 = AdminTasksModuleScss.h1;

let sub = AdminTasksModuleScss.sub;

let btn = AdminTasksModuleScss.btn;

let card = AdminTasksModuleScss.card;

let h2 = AdminTasksModuleScss.h2;

let grid = AdminTasksModuleScss.grid;

let field = AdminTasksModuleScss.field;

let label = AdminTasksModuleScss.label;

let input = AdminTasksModuleScss.input;

let textarea = AdminTasksModuleScss.textarea;

let row = AdminTasksModuleScss.row;

let smallBtn = AdminTasksModuleScss.smallBtn;

let badge = AdminTasksModuleScss.badge;

let error = AdminTasksModuleScss.error;

let list = AdminTasksModuleScss.list;

let testRow = AdminTasksModuleScss.testRow;

let left = AdminTasksModuleScss.left;

let title = AdminTasksModuleScss.title;

let meta = AdminTasksModuleScss.meta;

let S = {
  page: page,
  top: top,
  h1: h1,
  sub: sub,
  btn: btn,
  card: card,
  h2: h2,
  grid: grid,
  field: field,
  label: label,
  input: input,
  textarea: textarea,
  row: row,
  smallBtn: smallBtn,
  badge: badge,
  error: error,
  list: list,
  testRow: testRow,
  left: left,
  title: title,
  meta: meta
};

function errMsg(e) {
  let m = Stdlib_JsExn.message(e);
  if (m !== undefined) {
    return m;
  } else {
    return "error";
  }
}

let jsonParse = (s => globalThis.JSON.parse(s));

let jsonStringify = (v => globalThis.JSON.stringify(v, null, 2));

function parseJson(s) {
  try {
    return jsonParse(s);
  } catch (exn) {
    return;
  }
}

function stringifyJson(j) {
  return jsonStringify(j);
}

function AdminTasks(props) {
  let match = React.useState(() => "");
  let setTitle = match[1];
  let title$1 = match[0];
  let match$1 = React.useState(() => "");
  let setStatement = match$1[1];
  let statement = match$1[0];
  let match$2 = React.useState(() => "");
  let setStarterCode = match$2[1];
  let starterCode = match$2[0];
  let match$3 = React.useState(() => "1");
  let setTopicId = match$3[1];
  let topicId = match$3[0];
  let match$4 = React.useState(() => false);
  let setCreating = match$4[1];
  let creating = match$4[0];
  let match$5 = React.useState(() => {});
  let setCreatedId = match$5[1];
  let createdId = match$5[0];
  let match$6 = React.useState(() => "");
  let setCreateErr = match$6[1];
  let createErr = match$6[0];
  let match$7 = React.useState(() => "");
  let setTaskId = match$7[1];
  let taskId = match$7[0];
  let match$8 = React.useState(() => []);
  let setTests = match$8[1];
  let tests = match$8[0];
  let match$9 = React.useState(() => false);
  let setLoadingTests = match$9[1];
  let loadingTests = match$9[0];
  let match$10 = React.useState(() => "");
  let setTestsErr = match$10[1];
  let testsErr = match$10[0];
  let match$11 = React.useState(() => "");
  let setNewName = match$11[1];
  let newName = match$11[0];
  let match$12 = React.useState(() => "0");
  let setNewOrder = match$12[1];
  let newOrder = match$12[0];
  let match$13 = React.useState(() => "");
  let setNewInput = match$13[1];
  let newInput = match$13[0];
  let match$14 = React.useState(() => "");
  let setNewExpected = match$14[1];
  let newExpected = match$14[0];
  let match$15 = React.useState(() => false);
  let setAdding = match$15[1];
  let adding = match$15[0];
  let loadTests = id => {
    if (id === "") {
      setTests(param => []);
      return setTestsErr(param => "");
    } else {
      setLoadingTests(param => true);
      setTestsErr(param => "");
      Stdlib_Promise.$$catch(AdminTestsApi.list(id).then(xs => {
        setTests(param => xs);
        setLoadingTests(param => false);
        return Promise.resolve();
      }), e => {
        setTestsErr(param => errMsg(e));
        setLoadingTests(param => false);
        return Promise.resolve();
      });
      return;
    }
  };
  React.useEffect(() => {
    loadTests(taskId);
  }, [taskId]);
  let onCreate = () => {
    setCreating(param => true);
    setCreateErr(param => "");
    setCreatedId(param => {});
    let dto = {
      topic_id: topicId,
      title: title$1,
      statement: statement,
      starter_code: starterCode,
      runner: undefined,
      runner_body: undefined
    };
    Stdlib_Promise.$$catch(AdminTasksApi.create(dto).then(r => {
      setCreatedId(param => r.id);
      setTaskId(param => r.id);
      setCreating(param => false);
      return Promise.resolve();
    }), e => {
      setCreateErr(param => errMsg(e));
      setCreating(param => false);
      return Promise.resolve();
    });
  };
  let onAddTest = () => {
    if (taskId === "") {
      return setTestsErr(param => "Task id is required");
    }
    let match = parseJson(newInput);
    let match$1 = parseJson(newExpected);
    if (match !== undefined && match$1 !== undefined) {
      setAdding(param => true);
      setTestsErr(param => "");
      let v = Stdlib_Int.fromString(newOrder, undefined);
      let order_index = v !== undefined ? v : 0;
      let t_name = newName === "" ? "test" : newName;
      let t = {
        name: t_name,
        input_json: match,
        expected_json: match$1,
        order_index: order_index
      };
      Stdlib_Promise.$$catch(AdminTestsApi.add(taskId, Belt_Array.make(1, t)).then(param => {
        setNewName(param => "");
        setNewInput(param => "");
        setNewExpected(param => "");
        setNewOrder(param => "0");
        setAdding(param => false);
        loadTests(taskId);
        return Promise.resolve();
      }), e => {
        setTestsErr(param => errMsg(e));
        setAdding(param => false);
        return Promise.resolve();
      });
      return;
    }
    setTestsErr(param => "Bad JSON in input_json or expected_json");
  };
  let tmp = createErr === "" ? null : JsxRuntime.jsx("div", {
      children: "Error: " + createErr,
      className: error
    });
  let tmp$1 = testsErr === "" ? null : JsxRuntime.jsx("div", {
      children: "Error: " + testsErr,
      className: error
    });
  let tmp$2;
  tmp$2 = loadingTests ? "Loading..." : (
      taskId === "" ? "Set task id to load tests." : "Count: " + tests.length.toString()
    );
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: "Tasks",
                className: h1
              }),
              JsxRuntime.jsx("div", {
                children: "Create tasks and manage tests.",
                className: sub
              })
            ]
          }),
          JsxRuntime.jsx(NextLink.make, {
            href: "/admin",
            className: btn,
            children: "Back"
          })
        ],
        className: top
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Create task",
            className: h2
          }),
          tmp,
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: "Topic id",
                    className: label
                  }),
                  JsxRuntime.jsx("input", {
                    className: input,
                    value: topicId,
                    onChange: e => setTopicId(param => e.target.value)
                  })
                ],
                className: field
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: "Title",
                    className: label
                  }),
                  JsxRuntime.jsx("input", {
                    className: input,
                    value: title$1,
                    onChange: e => setTitle(param => e.target.value)
                  })
                ],
                className: field
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: "Statement",
                    className: label
                  }),
                  JsxRuntime.jsx("textarea", {
                    className: textarea,
                    value: statement,
                    onChange: e => setStatement(param => e.target.value)
                  })
                ],
                className: field
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: "Starter code",
                    className: label
                  }),
                  JsxRuntime.jsx("textarea", {
                    className: textarea,
                    value: starterCode,
                    onChange: e => setStarterCode(param => e.target.value)
                  })
                ],
                className: field
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("button", {
                    children: creating ? "Creating..." : "Create",
                    className: smallBtn,
                    disabled: creating,
                    onClick: param => onCreate()
                  }),
                  createdId !== undefined ? JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                          children: "Created id: " + createdId,
                          className: badge
                        }),
                        JsxRuntime.jsx(NextLink.make, {
                          href: "/task/" + createdId,
                          className: smallBtn,
                          children: "Open task"
                        })
                      ],
                      className: row
                    }) : null
                ],
                className: row
              })
            ],
            className: grid
          })
        ],
        className: card
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Manage task",
            className: h2
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: "Task id",
                    className: label
                  }),
                  JsxRuntime.jsx("input", {
                    className: input,
                    value: taskId,
                    onChange: e => setTaskId(param => e.target.value)
                  })
                ],
                className: field
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("button", {
                    children: loadingTests ? "Loading tests..." : "Reload tests",
                    className: smallBtn,
                    disabled: loadingTests,
                    onClick: param => loadTests(taskId)
                  }),
                  JsxRuntime.jsx("button", {
                    children: "Archive",
                    className: smallBtn,
                    disabled: taskId === "",
                    onClick: param => {
                      if (taskId !== "") {
                        AdminTasksApi.archive(taskId).then(param => Promise.resolve());
                        return;
                      }
                    }
                  }),
                  JsxRuntime.jsx("button", {
                    children: "Unarchive",
                    className: smallBtn,
                    disabled: taskId === "",
                    onClick: param => {
                      if (taskId !== "") {
                        AdminTasksApi.unarchive(taskId).then(param => Promise.resolve());
                        return;
                      }
                    }
                  })
                ],
                className: row
              })
            ],
            className: grid
          })
        ],
        className: card
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Add test",
            className: h2
          }),
          tmp$1,
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: "Name",
                    className: label
                  }),
                  JsxRuntime.jsx("input", {
                    className: input,
                    value: newName,
                    onChange: e => setNewName(param => e.target.value)
                  })
                ],
                className: field
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: "Order index",
                    className: label
                  }),
                  JsxRuntime.jsx("input", {
                    className: input,
                    value: newOrder,
                    onChange: e => setNewOrder(param => e.target.value)
                  })
                ],
                className: field
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: "input_json",
                    className: label
                  }),
                  JsxRuntime.jsx("textarea", {
                    className: textarea,
                    value: newInput,
                    onChange: e => setNewInput(param => e.target.value)
                  })
                ],
                className: field
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: "expected_json",
                    className: label
                  }),
                  JsxRuntime.jsx("textarea", {
                    className: textarea,
                    value: newExpected,
                    onChange: e => setNewExpected(param => e.target.value)
                  })
                ],
                className: field
              }),
              JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx("button", {
                  children: adding ? "Adding..." : "Add test",
                  className: smallBtn,
                  disabled: adding,
                  onClick: param => onAddTest()
                }),
                className: row
              })
            ],
            className: grid
          })
        ],
        className: card
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Tests",
            className: h2
          }),
          JsxRuntime.jsx("div", {
            children: tmp$2,
            className: sub
          }),
          JsxRuntime.jsx("div", {
            children: Belt_Array.map(tests, t => JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("div", {
                      children: t.name + " • " + t.id,
                      className: title
                    }),
                    JsxRuntime.jsx("div", {
                      children: "input: " + jsonStringify(t.input_json),
                      className: meta
                    }),
                    JsxRuntime.jsx("div", {
                      children: "expected: " + jsonStringify(t.expected_json),
                      className: meta
                    })
                  ],
                  className: left
                }),
                JsxRuntime.jsx("button", {
                  children: "Delete",
                  className: smallBtn,
                  onClick: param => {
                    let id = t.id;
                    AdminTestsApi.deleteOne(id).then(param => {
                      loadTests(taskId);
                      return Promise.resolve();
                    });
                  }
                })
              ],
              className: testRow
            }, t.id)),
            className: list
          })
        ],
        className: card
      })
    ],
    className: page
  });
}

let make = AdminTasks;

export {
  S,
  errMsg,
  jsonParse,
  jsonStringify,
  parseJson,
  stringifyJson,
  make,
}
/* page Not a pure module */
