// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NextLink from "../../bindings/NextLink.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as AdminSubmissionsModuleScss from "./AdminSubmissions.module.scss";

let page = AdminSubmissionsModuleScss.page;

let top = AdminSubmissionsModuleScss.top;

let h1 = AdminSubmissionsModuleScss.h1;

let sub = AdminSubmissionsModuleScss.sub;

let btn = AdminSubmissionsModuleScss.btn;

let card = AdminSubmissionsModuleScss.card;

let h2 = AdminSubmissionsModuleScss.h2;

let list = AdminSubmissionsModuleScss.list;

let item = AdminSubmissionsModuleScss.item;

let dot = AdminSubmissionsModuleScss.dot;

let S = {
  page: page,
  top: top,
  h1: h1,
  sub: sub,
  btn: btn,
  card: card,
  h2: h2,
  list: list,
  item: item,
  dot: dot
};

function AdminSubmissions(props) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: "Submissions",
                className: h1
              }),
              JsxRuntime.jsx("div", {
                children: "Search and inspect submissions.",
                className: sub
              })
            ]
          }),
          JsxRuntime.jsx(NextLink.make, {
            href: "/admin",
            className: btn,
            children: "Back"
          })
        ],
        className: top
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Planned",
            className: h2
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    className: dot
                  }),
                  JsxRuntime.jsx("div", {
                    children: "Filter by task/user/status."
                  })
                ],
                className: item
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    className: dot
                  }),
                  JsxRuntime.jsx("div", {
                    children: "Open any submission by id."
                  })
                ],
                className: item
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    className: dot
                  }),
                  JsxRuntime.jsx("div", {
                    children: "Moderation tools if needed."
                  })
                ],
                className: item
              })
            ],
            className: list
          })
        ],
        className: card
      })
    ],
    className: page
  });
}

let make = AdminSubmissions;

export {
  S,
  make,
}
/* page Not a pure module */
