// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NextLink from "../../bindings/NextLink.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as AdminModuleScss from "./Admin.module.scss";

let page = AdminModuleScss.page;

let top = AdminModuleScss.top;

let h1 = AdminModuleScss.h1;

let sub = AdminModuleScss.sub;

let grid = AdminModuleScss.grid;

let card = AdminModuleScss.card;

let cardTitle = AdminModuleScss.cardTitle;

let cardSub = AdminModuleScss.cardSub;

let cardMeta = AdminModuleScss.cardMeta;

let S = {
  page: page,
  top: top,
  h1: h1,
  sub: sub,
  grid: grid,
  card: card,
  cardTitle: cardTitle,
  cardSub: cardSub,
  cardMeta: cardMeta
};

function Admin(props) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: "Admin",
              className: h1
            }),
            JsxRuntime.jsx("div", {
              children: "Manage content and users.",
              className: sub
            })
          ]
        }),
        className: top
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs(NextLink.make, {
            href: "/admin/users",
            className: card,
            children: [
              JsxRuntime.jsx("div", {
                children: "Users",
                className: cardTitle
              }),
              JsxRuntime.jsx("div", {
                children: "Roles, ratings, accounts.",
                className: cardSub
              }),
              JsxRuntime.jsx("div", {
                children: "Soon",
                className: cardMeta
              })
            ]
          }),
          JsxRuntime.jsxs(NextLink.make, {
            href: "/admin/topics",
            className: card,
            children: [
              JsxRuntime.jsx("div", {
                children: "Topics",
                className: cardTitle
              }),
              JsxRuntime.jsx("div", {
                children: "Create and edit topics.",
                className: cardSub
              }),
              JsxRuntime.jsx("div", {
                children: "Soon",
                className: cardMeta
              })
            ]
          }),
          JsxRuntime.jsxs(NextLink.make, {
            href: "/admin/tasks",
            className: card,
            children: [
              JsxRuntime.jsx("div", {
                children: "Tasks",
                className: cardTitle
              }),
              JsxRuntime.jsx("div", {
                children: "Create tasks and tests.",
                className: cardSub
              }),
              JsxRuntime.jsx("div", {
                children: "Soon",
                className: cardMeta
              })
            ]
          }),
          JsxRuntime.jsxs(NextLink.make, {
            href: "/admin/submissions",
            className: card,
            children: [
              JsxRuntime.jsx("div", {
                children: "Submissions",
                className: cardTitle
              }),
              JsxRuntime.jsx("div", {
                children: "Review and grade.",
                className: cardSub
              }),
              JsxRuntime.jsx("div", {
                children: "Soon",
                className: cardMeta
              })
            ]
          })
        ],
        className: grid
      })
    ],
    className: page
  });
}

let make = Admin;

export {
  S,
  make,
}
/* page Not a pure module */
