// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NextLink from "../../bindings/NextLink.res.mjs";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as SubmissionsApi from "../../api/submissions/SubmissionsApi.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as AdminSubmissionsModuleScss from "./AdminSubmissions.module.scss";
import AdminGuardJs from "../../shared/auth/AdminGuard.js";

let page = AdminSubmissionsModuleScss.page;

let top = AdminSubmissionsModuleScss.top;

let h1 = AdminSubmissionsModuleScss.h1;

let sub = AdminSubmissionsModuleScss.sub;

let btn = AdminSubmissionsModuleScss.btn;

let card = AdminSubmissionsModuleScss.card;

let h2 = AdminSubmissionsModuleScss.h2;

let grid = AdminSubmissionsModuleScss.grid;

let field = AdminSubmissionsModuleScss.field;

let label = AdminSubmissionsModuleScss.label;

let input = AdminSubmissionsModuleScss.input;

let row = AdminSubmissionsModuleScss.row;

let smallBtn = AdminSubmissionsModuleScss.smallBtn;

let pill = AdminSubmissionsModuleScss.pill;

let error = AdminSubmissionsModuleScss.error;

let pre = AdminSubmissionsModuleScss.pre;

let S = {
  page: page,
  top: top,
  h1: h1,
  sub: sub,
  btn: btn,
  card: card,
  h2: h2,
  grid: grid,
  field: field,
  label: label,
  input: input,
  row: row,
  smallBtn: smallBtn,
  pill: pill,
  error: error,
  pre: pre
};

let adminGuard = AdminGuardJs;

function errMsg(e) {
  let m = Stdlib_JsExn.message(e);
  if (m !== undefined) {
    return m;
  } else {
    return "error";
  }
}

let jsonStringify = (v => globalThis.JSON.stringify(v, null, 2));

function stringifyJson(j) {
  return jsonStringify(j);
}

function AdminSubmissions(props) {
  let match = React.useState(() => "");
  let setId = match[1];
  let id = match[0];
  let match$1 = React.useState(() => false);
  let setLoading = match$1[1];
  let loading = match$1[0];
  let match$2 = React.useState(() => "");
  let setErr = match$2[1];
  let err = match$2[0];
  let match$3 = React.useState(() => {});
  let setItem = match$3[1];
  let item = match$3[0];
  let tmp = err === "" ? null : JsxRuntime.jsx("div", {
      children: "Error: " + err,
      className: error
    });
  return JsxRuntime.jsxs("div", {
    children: [
      React.createElement(adminGuard, undefined),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: "Submissions",
                className: h1
              }),
              JsxRuntime.jsx("div", {
                children: "Lookup submission by id.",
                className: sub
              })
            ]
          }),
          JsxRuntime.jsx(NextLink.make, {
            href: "/admin",
            className: btn,
            children: "Back"
          })
        ],
        className: top
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Find",
            className: h2
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: "Submission id",
                    className: label
                  }),
                  JsxRuntime.jsx("input", {
                    className: input,
                    value: id,
                    onChange: e => setId(param => e.target.value)
                  })
                ],
                className: field
              }),
              JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx("button", {
                  children: loading ? "Loading..." : "Load",
                  className: smallBtn,
                  disabled: loading,
                  onClick: param => {
                    if (id.trim() === "") {
                      setErr(param => "Submission id required");
                      return setItem(param => {});
                    } else {
                      setLoading(param => true);
                      setErr(param => "");
                      setItem(param => {});
                      Stdlib_Promise.$$catch(SubmissionsApi.getOne(id).then(s => {
                        setItem(param => s);
                        setLoading(param => false);
                        return Promise.resolve();
                      }), e => {
                        setErr(param => errMsg(e));
                        setLoading(param => false);
                        return Promise.resolve();
                      });
                      return;
                    }
                  }
                }),
                className: row
              })
            ],
            className: grid
          }),
          tmp
        ],
        className: card
      }),
      item !== undefined ? JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: "Result",
              className: h2
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                  children: "status " + item.status,
                  className: pill
                }),
                JsxRuntime.jsx("div", {
                  children: "score " + item.score.toString(),
                  className: pill
                }),
                JsxRuntime.jsx("div", {
                  children: "tests " + item.passed_tests.toString() + "/" + item.total_tests.toString(),
                  className: pill
                })
              ],
              className: row
            }),
            JsxRuntime.jsx("div", {
              children: jsonStringify(item.result),
              className: pre
            })
          ],
          className: card
        }) : null
    ],
    className: page
  });
}

let make = AdminSubmissions;

export {
  S,
  adminGuard,
  errMsg,
  jsonStringify,
  stringifyJson,
  make,
}
/* page Not a pure module */
