// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NextLink from "../../bindings/NextLink.res.mjs";
import * as UsersApi from "../../api/users/UsersApi.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as AdminTasksApi from "../../api/admin/AdminTasksApi.res.mjs";
import * as AdminTopicsApi from "../../api/admin/AdminTopicsApi.res.mjs";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as AdminModuleScss from "./Admin.module.scss";
import AdminGuardJs from "../../shared/auth/AdminGuard.js";

let page = AdminModuleScss.page;

let top = AdminModuleScss.top;

let h1 = AdminModuleScss.h1;

let sub = AdminModuleScss.sub;

let grid = AdminModuleScss.grid;

let card = AdminModuleScss.card;

let cardTitle = AdminModuleScss.cardTitle;

let cardSub = AdminModuleScss.cardSub;

let cardMeta = AdminModuleScss.cardMeta;

let S = {
  page: page,
  top: top,
  h1: h1,
  sub: sub,
  grid: grid,
  card: card,
  cardTitle: cardTitle,
  cardSub: cardSub,
  cardMeta: cardMeta
};

let adminGuard = AdminGuardJs;

function errMsg(e) {
  let m = Stdlib_JsExn.message(e);
  if (m !== undefined) {
    return m;
  } else {
    return "error";
  }
}

function Admin(props) {
  let match = React.useState(() => true);
  let setLoading = match[1];
  let match$1 = React.useState(() => "");
  let setErr = match$1[1];
  let err = match$1[0];
  let match$2 = React.useState(() => 0);
  let setTopicsCount = match$2[1];
  let topicsCount = match$2[0];
  let match$3 = React.useState(() => 0);
  let setTasksCount = match$3[1];
  let tasksCount = match$3[0];
  let match$4 = React.useState(() => []);
  let setTopUsers = match$4[1];
  let load = () => {
    setLoading(param => true);
    setErr(param => "");
    Stdlib_Promise.$$catch(AdminTopicsApi.listAdmin().then(ts => {
      setTopicsCount(param => ts.length);
      return AdminTasksApi.list();
    }).then(tasks => {
      setTasksCount(param => tasks.length);
      return UsersApi.leaderboard(undefined, undefined);
    }).then(lb => {
      setTopUsers(param => Belt_Array.slice(lb.items, 0, 5));
      setLoading(param => false);
      return Promise.resolve();
    }), e => {
      setErr(param => errMsg(e));
      setLoading(param => false);
      return Promise.resolve();
    });
  };
  React.useEffect(() => {
    load();
  }, []);
  let tmp;
  tmp = match[0] ? "Loading..." : (
      err === "" ? "Topics: " + topicsCount.toString() + " • Tasks: " + tasksCount.toString() : "Error: " + err
    );
  return JsxRuntime.jsxs("div", {
    children: [
      React.createElement(adminGuard, undefined),
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: "Admin",
              className: h1
            }),
            JsxRuntime.jsx("div", {
              children: tmp,
              className: sub
            })
          ]
        }),
        className: top
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs(NextLink.make, {
            href: "/admin/topics",
            className: card,
            children: [
              JsxRuntime.jsx("div", {
                children: "Topics",
                className: cardTitle
              }),
              JsxRuntime.jsx("div", {
                children: "Create topics, paragraphs, archive/unarchive.",
                className: cardSub
              }),
              JsxRuntime.jsx("div", {
                children: topicsCount.toString() + " total",
                className: cardMeta
              })
            ]
          }),
          JsxRuntime.jsxs(NextLink.make, {
            href: "/admin/tasks",
            className: card,
            children: [
              JsxRuntime.jsx("div", {
                children: "Tasks",
                className: cardTitle
              }),
              JsxRuntime.jsx("div", {
                children: "Create tasks, manage tests, archive/unarchive.",
                className: cardSub
              }),
              JsxRuntime.jsx("div", {
                children: tasksCount.toString() + " total",
                className: cardMeta
              })
            ]
          }),
          JsxRuntime.jsxs(NextLink.make, {
            href: "/admin/users",
            className: card,
            children: [
              JsxRuntime.jsx("div", {
                children: "Users",
                className: cardTitle
              }),
              JsxRuntime.jsx("div", {
                children: "Me + leaderboard pagination.",
                className: cardSub
              }),
              JsxRuntime.jsx("div", {
                children: "Top: " + match$4[0].length.toString(),
                className: cardMeta
              })
            ]
          }),
          JsxRuntime.jsxs(NextLink.make, {
            href: "/admin/submissions",
            className: card,
            children: [
              JsxRuntime.jsx("div", {
                children: "Submissions",
                className: cardTitle
              }),
              JsxRuntime.jsx("div", {
                children: "Lookup submission by id.",
                className: cardSub
              }),
              JsxRuntime.jsx("div", {
                children: "By id",
                className: cardMeta
              })
            ]
          })
        ],
        className: grid
      })
    ],
    className: page
  });
}

let make = Admin;

export {
  S,
  adminGuard,
  errMsg,
  make,
}
/* page Not a pure module */
