// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NextLink from "../../bindings/NextLink.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as AdminUsersModuleScss from "./AdminUsers.module.scss";

let page = AdminUsersModuleScss.page;

let top = AdminUsersModuleScss.top;

let h1 = AdminUsersModuleScss.h1;

let sub = AdminUsersModuleScss.sub;

let btn = AdminUsersModuleScss.btn;

let card = AdminUsersModuleScss.card;

let h2 = AdminUsersModuleScss.h2;

let list = AdminUsersModuleScss.list;

let item = AdminUsersModuleScss.item;

let dot = AdminUsersModuleScss.dot;

let S = {
  page: page,
  top: top,
  h1: h1,
  sub: sub,
  btn: btn,
  card: card,
  h2: h2,
  list: list,
  item: item,
  dot: dot
};

function AdminUsers(props) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: "Users",
                className: h1
              }),
              JsxRuntime.jsx("div", {
                children: "List users and manage roles.",
                className: sub
              })
            ]
          }),
          JsxRuntime.jsx(NextLink.make, {
            href: "/admin",
            className: btn,
            children: "Back"
          })
        ],
        className: top
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Planned",
            className: h2
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    className: dot
                  }),
                  JsxRuntime.jsx("div", {
                    children: "Users list with search and pagination."
                  })
                ],
                className: item
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    className: dot
                  }),
                  JsxRuntime.jsx("div", {
                    children: "Change role (user/admin)."
                  })
                ],
                className: item
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    className: dot
                  }),
                  JsxRuntime.jsx("div", {
                    children: "Open user profile and submissions."
                  })
                ],
                className: item
              })
            ],
            className: list
          })
        ],
        className: card
      })
    ],
    className: page
  });
}

let make = AdminUsers;

export {
  S,
  make,
}
/* page Not a pure module */
