// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NextLink from "../../bindings/NextLink.res.mjs";
import * as UsersApi from "../../api/users/UsersApi.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as AdminTasksApi from "../../api/admin/AdminTasksApi.res.mjs";
import * as AdminTopicsApi from "../../api/admin/AdminTopicsApi.res.mjs";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as AdminHomeModuleScss from "./AdminHome.module.scss";
import AdminGuardJs from "../../shared/auth/AdminGuard.js";

let page = AdminHomeModuleScss.page;

let top = AdminHomeModuleScss.top;

let h1 = AdminHomeModuleScss.h1;

let sub = AdminHomeModuleScss.sub;

let navCard = AdminHomeModuleScss.navCard;

let navBtn = AdminHomeModuleScss.navBtn;

let card = AdminHomeModuleScss.card;

let h2 = AdminHomeModuleScss.h2;

let list = AdminHomeModuleScss.list;

let item = AdminHomeModuleScss.item;

let dot = AdminHomeModuleScss.dot;

let S = {
  page: page,
  top: top,
  h1: h1,
  sub: sub,
  navCard: navCard,
  navBtn: navBtn,
  card: card,
  h2: h2,
  list: list,
  item: item,
  dot: dot
};

let adminGuard = AdminGuardJs;

function errMsg(e) {
  let m = Stdlib_JsExn.message(e);
  if (m !== undefined) {
    return m;
  } else {
    return "error";
  }
}

function AdminHome(props) {
  let match = React.useState(() => true);
  let setLoading = match[1];
  let match$1 = React.useState(() => "");
  let setErr = match$1[1];
  let err = match$1[0];
  let match$2 = React.useState(() => 0);
  let setTopicsCount = match$2[1];
  let topicsCount = match$2[0];
  let match$3 = React.useState(() => 0);
  let setTasksCount = match$3[1];
  let tasksCount = match$3[0];
  let match$4 = React.useState(() => []);
  let setTopUsers = match$4[1];
  let load = () => {
    setLoading(param => true);
    setErr(param => "");
    Stdlib_Promise.$$catch(AdminTopicsApi.listAdmin().then(ts => {
      setTopicsCount(param => ts.length);
      return AdminTasksApi.list();
    }).then(tasks => {
      setTasksCount(param => tasks.length);
      return UsersApi.leaderboard(undefined, undefined);
    }).then(lb => {
      setTopUsers(param => Belt_Array.slice(lb.items, 0, 5));
      setLoading(param => false);
      return Promise.resolve();
    }), e => {
      setErr(param => errMsg(e));
      setLoading(param => false);
      return Promise.resolve();
    });
  };
  React.useEffect(() => {
    load();
  }, []);
  let tmp;
  tmp = match[0] ? "Loading..." : (
      err === "" ? "Topics: " + topicsCount.toString() + " • Tasks: " + tasksCount.toString() : "Error: " + err
    );
  return JsxRuntime.jsxs("div", {
    children: [
      React.createElement(adminGuard, undefined),
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: "Admin",
              className: h1
            }),
            JsxRuntime.jsx("div", {
              children: tmp,
              className: sub
            })
          ]
        }),
        className: top
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx(NextLink.make, {
            href: "/admin/users",
            className: navBtn,
            children: "Users"
          }),
          JsxRuntime.jsx(NextLink.make, {
            href: "/admin/topics",
            className: navBtn,
            children: "Topics"
          }),
          JsxRuntime.jsx(NextLink.make, {
            href: "/admin/tasks",
            className: navBtn,
            children: "Tasks"
          }),
          JsxRuntime.jsx(NextLink.make, {
            href: "/admin/submissions",
            className: navBtn,
            children: "Submissions"
          })
        ],
        className: navCard
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Overview",
            className: h2
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    className: dot
                  }),
                  JsxRuntime.jsx("div", {
                    children: "topics: " + topicsCount.toString()
                  })
                ],
                className: item
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    className: dot
                  }),
                  JsxRuntime.jsx("div", {
                    children: "tasks: " + tasksCount.toString()
                  })
                ],
                className: item
              })
            ],
            className: list
          })
        ],
        className: card
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Top users",
            className: h2
          }),
          JsxRuntime.jsx("div", {
            children: Belt_Array.map(match$4[0], u => JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                  className: dot
                }),
                JsxRuntime.jsx("div", {
                  children: u.nickname + " • " + u.rating.toString()
                })
              ],
              className: item
            }, u.id)),
            className: list
          })
        ],
        className: card
      })
    ],
    className: page
  });
}

let make = AdminHome;

export {
  S,
  adminGuard,
  errMsg,
  make,
}
/* page Not a pure module */
