// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NextLink from "../../bindings/NextLink.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as AdminHomeModuleScss from "./AdminHome.module.scss";

let page = AdminHomeModuleScss.page;

let top = AdminHomeModuleScss.top;

let h1 = AdminHomeModuleScss.h1;

let sub = AdminHomeModuleScss.sub;

let navCard = AdminHomeModuleScss.navCard;

let navBtn = AdminHomeModuleScss.navBtn;

let card = AdminHomeModuleScss.card;

let h2 = AdminHomeModuleScss.h2;

let list = AdminHomeModuleScss.list;

let item = AdminHomeModuleScss.item;

let dot = AdminHomeModuleScss.dot;

let S = {
  page: page,
  top: top,
  h1: h1,
  sub: sub,
  navCard: navCard,
  navBtn: navBtn,
  card: card,
  h2: h2,
  list: list,
  item: item,
  dot: dot
};

function AdminHome(props) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: "Admin",
              className: h1
            }),
            JsxRuntime.jsx("div", {
              children: "Manage users, topics, tasks and submissions.",
              className: sub
            })
          ]
        }),
        className: top
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx(NextLink.make, {
            href: "/admin/users",
            className: navBtn,
            children: "Users"
          }),
          JsxRuntime.jsx(NextLink.make, {
            href: "/admin/topics",
            className: navBtn,
            children: "Topics"
          }),
          JsxRuntime.jsx(NextLink.make, {
            href: "/admin/tasks",
            className: navBtn,
            children: "Tasks"
          }),
          JsxRuntime.jsx(NextLink.make, {
            href: "/admin/submissions",
            className: navBtn,
            children: "Submissions"
          })
        ],
        className: navCard
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Next steps",
            className: h2
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    className: dot
                  }),
                  JsxRuntime.jsx("div", {
                    children: "Users: list, change role, inspect profile."
                  })
                ],
                className: item
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    className: dot
                  }),
                  JsxRuntime.jsx("div", {
                    children: "Topics: create/edit/delete topics."
                  })
                ],
                className: item
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    className: dot
                  }),
                  JsxRuntime.jsx("div", {
                    children: "Tasks: create/edit tasks, publish/unpublish."
                  })
                ],
                className: item
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    className: dot
                  }),
                  JsxRuntime.jsx("div", {
                    children: "Submissions: filter by task/user/status, open any submission."
                  })
                ],
                className: item
              })
            ],
            className: list
          })
        ],
        className: card
      })
    ],
    className: page
  });
}

let make = AdminHome;

export {
  S,
  make,
}
/* page Not a pure module */
