// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NextLink from "../../bindings/NextLink.res.mjs";
import * as UsersApi from "../../api/users/UsersApi.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as AdminUsersModuleScss from "./AdminUsers.module.scss";
import AdminGuardJs from "../../shared/auth/AdminGuard.js";

let page = AdminUsersModuleScss.page;

let top = AdminUsersModuleScss.top;

let h1 = AdminUsersModuleScss.h1;

let sub = AdminUsersModuleScss.sub;

let btn = AdminUsersModuleScss.btn;

let card = AdminUsersModuleScss.card;

let h2 = AdminUsersModuleScss.h2;

let list = AdminUsersModuleScss.list;

let item = AdminUsersModuleScss.item;

let dot = AdminUsersModuleScss.dot;

let row = AdminUsersModuleScss.row;

let input = AdminUsersModuleScss.input;

let smallBtn = AdminUsersModuleScss.smallBtn;

let pill = AdminUsersModuleScss.pill;

let error = AdminUsersModuleScss.error;

let S = {
  page: page,
  top: top,
  h1: h1,
  sub: sub,
  btn: btn,
  card: card,
  h2: h2,
  list: list,
  item: item,
  dot: dot,
  row: row,
  input: input,
  smallBtn: smallBtn,
  pill: pill,
  error: error
};

let adminGuard = AdminGuardJs;

function errMsg(e) {
  let m = Stdlib_JsExn.message(e);
  if (m !== undefined) {
    return m;
  } else {
    return "error";
  }
}

function $$parseInt(s) {
  let v = Stdlib_Int.fromString(s.trim(), undefined);
  if (v !== undefined) {
    return v;
  }
}

function AdminUsers(props) {
  let match = React.useState(() => {});
  let setMe = match[1];
  let me = match[0];
  let match$1 = React.useState(() => []);
  let setItems = match$1[1];
  let items = match$1[0];
  let match$2 = React.useState(() => true);
  let setLoading = match$2[1];
  let loading = match$2[0];
  let match$3 = React.useState(() => "");
  let setErr = match$3[1];
  let err = match$3[0];
  let match$4 = React.useState(() => 25);
  let setLimit = match$4[1];
  let limit = match$4[0];
  let match$5 = React.useState(() => 0);
  let setOffset = match$5[1];
  let offset = match$5[0];
  let load = (limit, offset) => {
    setLoading(param => true);
    setErr(param => "");
    Stdlib_Promise.$$catch(UsersApi.me().then(m => {
      setMe(param => m);
      return UsersApi.leaderboard(limit, offset);
    }).then(lb => {
      setItems(param => lb.items);
      setLoading(param => false);
      return Promise.resolve();
    }), e => {
      setErr(param => errMsg(e));
      setLoading(param => false);
      return Promise.resolve();
    });
  };
  React.useEffect(() => {
    load(limit, offset);
  }, []);
  let onPrev = () => {
    let nextOffset = 0 > (offset - limit | 0) ? 0 : offset - limit | 0;
    setOffset(param => nextOffset);
    load(limit, nextOffset);
  };
  let onNext = () => {
    let nextOffset = offset + limit | 0;
    setOffset(param => nextOffset);
    load(limit, nextOffset);
  };
  let tmp;
  tmp = loading ? "Loading..." : (
      err === "" ? "Rows: " + items.length.toString() : "Error: " + err
    );
  let tmp$1 = err === "" ? null : JsxRuntime.jsx("div", {
      children: "Error: " + err,
      className: error
    });
  return JsxRuntime.jsxs("div", {
    children: [
      React.createElement(adminGuard, undefined),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: "Users",
                className: h1
              }),
              JsxRuntime.jsx("div", {
                children: tmp,
                className: sub
              })
            ]
          }),
          JsxRuntime.jsx(NextLink.make, {
            href: "/admin",
            className: btn,
            children: "Back"
          })
        ],
        className: top
      }),
      tmp$1,
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Me",
            className: h2
          }),
          JsxRuntime.jsx("div", {
            children: me !== undefined ? JsxRuntime.jsxs(JsxRuntime.Fragment, {
                children: [
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                        className: dot
                      }),
                      JsxRuntime.jsx("div", {
                        children: "nickname: " + me.nickname
                      })
                    ],
                    className: item
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                        className: dot
                      }),
                      JsxRuntime.jsx("div", {
                        children: "email: " + me.email
                      })
                    ],
                    className: item
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                        className: dot
                      }),
                      JsxRuntime.jsx("div", {
                        children: "role: " + me.role
                      })
                    ],
                    className: item
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                        className: dot
                      }),
                      JsxRuntime.jsx("div", {
                        children: "rating: " + me.rating.toString()
                      })
                    ],
                    className: item
                  })
                ]
              }) : JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    className: dot
                  }),
                  JsxRuntime.jsx("div", {
                    children: "—"
                  })
                ],
                className: item
              }),
            className: list
          })
        ],
        className: card
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Leaderboard",
            className: h2
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: "offset " + offset.toString(),
                className: pill
              }),
              JsxRuntime.jsx("div", {
                children: "limit " + limit.toString(),
                className: pill
              })
            ],
            className: row
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: "limit",
                className: pill
              }),
              JsxRuntime.jsx("input", {
                className: input,
                value: limit.toString(),
                onChange: e => {
                  let v = $$parseInt(e.target.value);
                  if (v !== undefined) {
                    return setLimit(param => {
                      if (1 > v) {
                        return 1;
                      } else {
                        return v;
                      }
                    });
                  }
                }
              }),
              JsxRuntime.jsx("div", {
                children: "offset",
                className: pill
              }),
              JsxRuntime.jsx("input", {
                className: input,
                value: offset.toString(),
                onChange: e => {
                  let v = $$parseInt(e.target.value);
                  if (v !== undefined) {
                    return setOffset(param => {
                      if (0 > v) {
                        return 0;
                      } else {
                        return v;
                      }
                    });
                  }
                }
              }),
              JsxRuntime.jsx("button", {
                children: loading ? "Reloading..." : "Apply",
                className: smallBtn,
                disabled: loading,
                onClick: param => load(limit, offset)
              }),
              JsxRuntime.jsx("button", {
                children: "Prev",
                className: smallBtn,
                disabled: loading || offset === 0,
                onClick: param => onPrev()
              }),
              JsxRuntime.jsx("button", {
                children: "Next",
                className: smallBtn,
                disabled: loading,
                onClick: param => onNext()
              })
            ],
            className: row
          }),
          JsxRuntime.jsx("div", {
            children: Belt_Array.map(items, u => JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                  className: dot
                }),
                JsxRuntime.jsx("div", {
                  children: u.nickname + " • " + u.rating.toString()
                })
              ],
              className: item
            }, u.id)),
            className: list
          })
        ],
        className: card
      })
    ],
    className: page
  });
}

let make = AdminUsers;

export {
  S,
  adminGuard,
  errMsg,
  $$parseInt,
  make,
}
/* page Not a pure module */
